#==========================================================
# COLORS
#==========================================================
[color]
include-file = /home/henryrocha/.config/polybar/colors.conf

#==========================================================
# BAR
#==========================================================
[bar/main]
# Bar size and placement
monitor = ${env:EXTERNAL_MONITOR1}
width = 100%
height = 25
bottom = true
fixed-center = true

# Bar colors
background = ${color.bground}
foreground = ${color.fground}

# Bar font
# font-0 = "Hack:style=Regular:size=10;3"
font-0 = "JetBrains Mono:style=Regular:size=10;3"
font-1 = "Font Awesome 5 Free:style=Regular:pixelsize=11;3"
font-2 = "Font Awesome 5 Free:style=Solid:pixelsize=11;3"
font-3 = "Font Awesome 5 Brands:pixelsize=11;3"

# Module position
modules-center = right1 bspwm left1 windowTitle left2

#==========================================================
# MODULES
#==========================================================
#------------
# LEFT
#------------
[module/bspwm]
type = internal/bspwm
pin-workspaces = true
inline-mode = false
enable-click = false
enable-scroll = false
reverse-scroll = false
fuzzy-match = true

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-default = 

format = <label-state>
format-background = ${color.shade1}
format-foreground = ${color.modulefg}

label-active = " %icon% "
label-urgent = " %icon% "
label-occupied = " %icon% "
label-empty = " %icon% "

label-active-foreground = ${color.accent}
label-occupied-foreground = ${color.yellow}
label-urgent-foreground = ${color.red}
label-empty-foreground = ${color.modulefg-alt}

[module/workspaces]
type = internal/xworkspaces
pin-workspaces = false
enable-click = true
enable-scroll = false

icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
icon-default = 

format = <label-state>
format-background = ${color.shade1}
format-foreground = ${color.modulefg}

label-active = " %icon% "
label-urgent = " %icon% "
label-occupied = " %icon% "
label-empty = " %icon% "

label-active-foreground = ${color.accent}
label-occupied-foreground = ${color.yellow}
label-urgent-foreground = ${color.red}
label-empty-foreground = ${color.modulefg-alt}

[module/windowTitle]
type = internal/xwindow
label-maxlen = 30
label-empty= " Arch Linux "

format-padding = 1
format-background = ${color.shade2}
format-foreground = ${color.modulefg}

#==========================================================
# ARROW MODULES
#==========================================================
[module/left1]
type = custom/text
content-font = 2
content-background = ${color.shade2}
content-foreground = ${color.shade1}
content = "%{T2}%{T-}"

[module/left2]
type = custom/text
content-font = 2
content-background = ${color.bground}
content-foreground = ${color.shade2}
content = "%{T2}%{T-}"

[module/right1]
type = custom/text
content-background = ${color.bground}
content-foreground = ${color.shade1}
content = "%{T3}%{T-}"
